[package]
name = "parsing"
version = "0.1.0"
authors = ["hehaowen00"]
edition = "2018"

[profile.bench]
codegen-units = 1
lto = "fat"

[profile.dev]
codegen-units = 1
lto = "fat"

[profile.release]
codegen-units = 1
lto = "fat"

[profile.test]
codegen-units = 1
lto = "fat"

[dependencies]
